version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build-tests:
    jobs:
      - run_tests:
          context: console_server_store

jobs:
  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            node ./node_modules/mocha/bin/mocha '**/*-test.js --exit

