version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build-tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: circleci/node:14 
        environment:
          PGHOST: $POSTGRES_HOST
          PGUSER: $POSTGRES_USER
          PORT: "3051"
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: $POSTGRES_TEST_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER

    steps:
      - checkout
      - run:
          name: Check Port 3051 Availability
          command: |
            while ! nc -z -v -w1 127.0.0.1 3051; do
              echo "Waiting for port 3051 to become available..."
              sleep 1
            done
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://127.0.0.1:3051 -timeout 1m
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test

