version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build-tests:
    jobs:
      - run_tests:
          context: console_server_store
jobs:
  run_tests:
    docker: #where things will be ran(docker, windows, mac, virtual machine)
      - image: circleci/node:7.10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: $POSTGRES_USER
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: $POSTGRES_TEST_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER
jobs:
  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test

