version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build-tests:
    jobs:
      - build
      - run_tests:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/go:1.17
        environment:
          PGHOST: 127.0.0.1
          POSTGRES_PASSWORD: Rs14251425!
      - image: circleci/postgres
    steps:
      - checkout

  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test

