version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build-tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: circleci/node:14 
        environment:
          PGHOST: 127.0.0.1
          PGUSER: $POSTGRES_USER
          NODE_ENV: test
      - image: cimg/postgres:14.0.0
        environment:
          POSTGRES_DB: $POSTGRES_TEST_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_USER: $POSTGRES_USER

    steps:
      - checkout
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test

