version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build-tests:
    jobs:
      - build
      - run_tests:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specify the desired Docker version
      - run:
          name: Check Docker Version
          command: docker --version
      - run:
          name: Check Docker Status
          command: |
            # Capture Docker info and store it in the DOCKER_INFO environment variable
            export DOCKER_INFO=$(docker info)
          when: always
      - run:
          name: Start PostgreSQL
          command: DOCKER_BUILDKIT=1 docker --log-level=debug run -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d -p 3051:5432 -e POSTGRES_DB=$POSTGRES_TEST_DB postgres
      - run:
          name: Check PostgreSQL Container Status
          command: |
            # Your Docker command to check the container status
            docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Command}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}"
            # Extract and store the PostgreSQL container name
            export POSTGRES_CONTAINER_NAME=$(docker ps --format "{{.Names}}" | grep postgres)
            echo "export POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME}" >> $BASH_ENV
          when: always
      - run:
          name: Set POSTGRES_HOST
          command: echo "export POSTGRES_HOST=host.docker.internal" >> $BASH_ENV
          no_output_timeout: 10s 

  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Display Environment Info
          command: |
            echo "Environment Info:"
            echo "Host name: $POSTGRES_HOST"
            echo "PostgreSQL container name: $POSTGRES_CONTAINER_NAME"
            echo "PostgreSQL database: $POSTGRES_TEST_DB"
            echo "Docker Info: $DOCKER_INFO"
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test

