version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build-tests:
    jobs:
      - build
      - run_tests:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Check Docker Version
          command: DOCKER_BUILDKIT=1 docker --log-level=debug --version
      - run:
          name: Check Docker Status
          command: DOCKER_BUILDKIT=1 docker --log-level=debug info
      - run:
          name: Start PostgreSQL
          command: DOCKER_BUILDKIT=1 docker --log-level=debug run -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d -p 5432:5432 postgres
      - run:
          name: Wait for PostgreSQL to Start
          command: sleep 10  # Wait for PostgreSQL to start (adjust as needed)
      - run:
          name: Set PGHOST
          command: echo "export PGHOST=127.0.0.1" >> $BASH_ENV
          no_output_timeout: 10s 

  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test


