jobs:
  run_tests:
    steps:
      - node/install:
          node-version: "20.8.1"
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            node ./node_modules/mocha/bin/mocha **/**/*_spec.js --exit
