version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build-tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: circleci/node:14 
        environment:
          PGHOST: $POSTGRES_HOST
          PGUSER: $POSTGRES_USER
          NODE_ENV: test
    services:
      - docker:dind  # Enable Docker-in-Docker
    steps:
      - checkout
      - run:
          name: Start PostgreSQL Container
          command: docker run -d -p 3051:5432 circleci/postgres:9.6.2-alpine
      - run:
          name: Check Port 5432 Availability
          command: |
            while ! nc -z -v -w1 127.0.0.1 3051; do
              echo "Waiting for port 3051 to become available..."
              sleep 1
            done
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://127.0.0.1:3051 -timeout 1m
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test
