version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  version: 2
  build-tests:
    jobs:
      - run_tests

jobs:
  run_tests:
    docker:
      - image: circleci/node:14 
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: circleci
    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: circleci

    steps:
      - run:
          name: install postgresql-client
          command: |
            sudo apt-get update
            apt-get add postgresql-client
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - checkout
      - run:
          name: Check Port 5432 Availability
          command: |
            while ! nc -z -v -w1 127.0.0.1 5432; do
              echo "Waiting for port 5432 to become available..."
              sleep 1
            done
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test

