version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  version: 2
  build-tests:
    jobs:
      - build
      - run_tests:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Specify the desired Docker version
      - run:
          name: Check Docker Version
          command: docker --version
      - run:
          name: Check Docker Status
          command: docker info
      - run:
          name: Start PostgreSQL
          command: DOCKER_BUILDKIT=1 docker --log-level=debug run -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d -p 3051:5432 -e POSTGRES_DB=$POSTGRES_TEST_DB postgres
      - run:
          name: Check PostgreSQL Container Status
          command: docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Command}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}"
      - run:
          name: Set PGHOST
          command: echo "export PGHOST=host.docker.internal" >> $BASH_ENV
          no_output_timeout: 10s 

  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Get Versions
          command: |
            node -v
            npm -v
      - run:
          name: Run Mocha Unit Tests
          command: |
            npm run test


